# -*- coding: utf-8 -*-
"""Task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cDS_K0g5SrkpG2EP9fEiR86r4DhXBahk
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

# Pip install method (recommended)

!pip install ultralytics==8.0.196

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model=yolov8n.pt conf=0.25 source='/content/1.png' save=True

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename='/content/runs/detect/predict/1.png', height=600)

model = YOLO(f'/content/yolov8n.pt')
results = model.predict(source='/content/1.png', conf=0.25)

results[0].boxes.xyxy

results[0].boxes.conf

results[0].boxes.cls

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow --quiet


from roboflow import Roboflow
rf = Roboflow(api_key="BvCctA5r7O9onzaSO6My")
project = rf.workspace("cricketballtrack-jf87p").project("cricket_ball_track")
dataset = project.version(2).download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8s.pt data=/content/datasets/cricket_ball_track-2/data.yaml epochs=100 imgsz=800 plots=True

!ls {HOME}/runs/detect/train/

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'/content/runs/detect/train/confusion_matrix.png', width=600)



# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'/content/runs/detect/train/results.png', width=700)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
Image(filename=f'/content/runs/detect/train/train_batch0.jpg', width=700)

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data=/content/datasets/cricket_ball_track-2/data.yaml

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}
!yolo task=detect mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.25 source=/content/2.png save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob(f'/content/runs/detect/predict4/2.png')[:3]:
      display(Image(filename=image_path, width=600))
      print("\n")